"""Porta di persistenza del dialogo (Protocol)."""

from typing import Protocol
from uuid import UUID

from whisper.dialogue.core.entities import Contact, Conversation, Message


class DialogueRepository(Protocol):
    async def add_conversation(self, conversation: Conversation) -> None: ...
    async def get_conversation(
        self, event_id: UUID, conversation_id: UUID
    ) -> Conversation | None: ...
    async def get_conversation_for_update(
        self, event_id: UUID, conversation_id: UUID
    ) -> Conversation | None:
        """Come get_conversation ma con lock di riga (serializza consensi/reveal concorrenti)."""
        ...
    async def find_missive_conversation(
        self, event_id: UUID, initiator_id: UUID, recipient_id: UUID
    ) -> Conversation | None: ...
    async def update_conversation(self, conversation: Conversation) -> None: ...
    async def add_message(self, message: Message) -> None: ...
    async def participant_is_guest(self, event_id: UUID, participant_id: UUID) -> bool: ...
    async def alias_taken(self, event_id: UUID, alias: str) -> bool: ...
    async def upsert_contact(self, contact: Contact) -> None: ...
    async def get_contacts(self, conversation_id: UUID) -> list[Contact]: ...
