"""Porte di persistenza del dominio identity (Protocol; impl in infrastructure)."""

from typing import Protocol
from uuid import UUID

from whisper.identity.core.entities import Event, Participant


class EventRepository(Protocol):
    async def add(self, event: Event) -> None: ...
    async def get(self, event_id: UUID) -> Event | None: ...
    async def get_by_join_code(self, join_code: str) -> Event | None: ...
    async def update(self, event: Event) -> None: ...


class ParticipantRepository(Protocol):
    async def add(self, participant: Participant) -> None: ...
    async def get(self, event_id: UUID, participant_id: UUID) -> Participant | None: ...
    async def get_host(self, event_id: UUID) -> Participant | None: ...
    async def get_by_pseudonym(self, event_id: UUID, pseudonym: str) -> Participant | None: ...
    async def update(self, participant: Participant) -> None: ...
    async def rotate_all_session_tokens(self, event_id: UUID) -> None: ...
