"""profile + photo + discovery

Revision ID: 11647a2af7ce
Revises: 9bae5c681db1
Create Date: 2026-07-17 20:42:03.657340
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '11647a2af7ce'
down_revision: str | None = '9bae5c681db1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_profile',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('secret_text', sa.Text(), nullable=True),
    sa.Column('motto', sa.Text(), nullable=True),
    sa.Column('avatar_seed', sa.Text(), nullable=False),
    sa.Column('accent_color', sa.Text(), nullable=True),
    sa.Column('clues', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('reveal_stage', sa.Enum('concealed', 'hinted', 'unmasked', name='profile_reveal_stage'), nullable=False),
    sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disclosed_publicly_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("accent_color IS NULL OR accent_color ~ '^#[0-9a-fA-F]{6}$'", name=op.f('ck_participant_profile_accent_hex')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_participant_profile_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_participant_profile_participant_id_participant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_profile'))
    )
    op.create_index('ix_participant_profile_event_id', 'participant_profile', ['event_id'], unique=False)
    op.create_index('uq_participant_profile_participant_id', 'participant_profile', ['participant_id'], unique=True)
    op.create_table('photo',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('hunter_participant_id', sa.Uuid(), nullable=False),
    sa.Column('subject_participant_id', sa.Uuid(), nullable=False),
    sa.Column('mysterious_title', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), server_default='image/jpeg', nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'under_review', 'removed', 'archived', name='photo_status'), nullable=False),
    sa.Column('subject_revealed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('revealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_reason', sa.Enum('subject_request', 'hunter_deleted', 'consent_revoked', 'host_action', 'moderation', name='photo_removal_reason'), nullable=True),
    sa.Column('removed_by_participant_id', sa.Uuid(), nullable=True),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct_guess_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type IN ('image/jpeg','image/png','image/webp')", name=op.f('ck_photo_content_type')),
    sa.CheckConstraint('char_length(mysterious_title) BETWEEN 1 AND 120', name=op.f('ck_photo_title_len')),
    sa.CheckConstraint('hunter_participant_id <> subject_participant_id', name=op.f('ck_photo_hunter_not_subject')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_photo_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hunter_participant_id'], ['participant.id'], name=op.f('fk_photo_hunter_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['removed_by_participant_id'], ['participant.id'], name=op.f('fk_photo_removed_by_participant_id_participant'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_participant_id'], ['participant.id'], name=op.f('fk_photo_subject_participant_id_participant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo'))
    )
    op.create_index('ix_photo_feed', 'photo', ['event_id', 'status', 'published_at', 'id'], unique=False)
    op.create_index('ix_photo_hunter', 'photo', ['event_id', 'hunter_participant_id'], unique=False)
    op.create_index('ix_photo_subject', 'photo', ['event_id', 'subject_participant_id'], unique=False)
    op.create_index('uq_photo_storage_key', 'photo', ['storage_key'], unique=True)
    op.create_table('whisper_comment',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('author_participant_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('visible', 'hidden', 'removed', name='comment_status'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(body)) BETWEEN 1 AND 500', name=op.f('ck_whisper_comment_body_len')),
    sa.ForeignKeyConstraint(['author_participant_id'], ['participant.id'], name=op.f('fk_whisper_comment_author_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_whisper_comment_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('fk_whisper_comment_photo_id_photo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whisper_comment'))
    )
    op.create_index('ix_whisper_comment_author', 'whisper_comment', ['author_participant_id'], unique=False)
    op.create_index('ix_whisper_comment_event_photo_created', 'whisper_comment', ['event_id', 'photo_id', 'created_at'], unique=False)
    op.create_table('whisper_discovery_state',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('total_guess_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct_guess_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_correct_guesser_id', sa.Uuid(), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reveal_state', sa.Enum('hidden', 'revealed', name='discovery_reveal_state'), nullable=False),
    sa.Column('revealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_whisper_discovery_state_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_correct_guesser_id'], ['participant.id'], name=op.f('fk_whisper_discovery_state_first_correct_guesser_id_participant'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('fk_whisper_discovery_state_photo_id_photo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whisper_discovery_state'))
    )
    op.create_index('ix_whisper_discovery_state_event', 'whisper_discovery_state', ['event_id'], unique=False)
    op.create_index('uq_whisper_discovery_state_photo', 'whisper_discovery_state', ['photo_id'], unique=True)
    op.create_table('whisper_guess',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('guesser_participant_id', sa.Uuid(), nullable=False),
    sa.Column('guessed_subject_participant_id', sa.Uuid(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('guess_rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_whisper_guess_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guessed_subject_participant_id'], ['participant.id'], name=op.f('fk_whisper_guess_guessed_subject_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guesser_participant_id'], ['participant.id'], name=op.f('fk_whisper_guess_guesser_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('fk_whisper_guess_photo_id_photo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whisper_guess'))
    )
    op.create_index('ix_whisper_guess_photo_correct', 'whisper_guess', ['photo_id'], unique=False, postgresql_where=sa.text('is_correct'))
    op.create_index('ix_whisper_guess_photo_guesser', 'whisper_guess', ['photo_id', 'guesser_participant_id'], unique=False)
    op.create_index('uq_whisper_guess_photo_guesser_candidate', 'whisper_guess', ['photo_id', 'guesser_participant_id', 'guessed_subject_participant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_whisper_guess_photo_guesser_candidate', table_name='whisper_guess')
    op.drop_index('ix_whisper_guess_photo_guesser', table_name='whisper_guess')
    op.drop_index('ix_whisper_guess_photo_correct', table_name='whisper_guess', postgresql_where=sa.text('is_correct'))
    op.drop_table('whisper_guess')
    op.drop_index('uq_whisper_discovery_state_photo', table_name='whisper_discovery_state')
    op.drop_index('ix_whisper_discovery_state_event', table_name='whisper_discovery_state')
    op.drop_table('whisper_discovery_state')
    op.drop_index('ix_whisper_comment_event_photo_created', table_name='whisper_comment')
    op.drop_index('ix_whisper_comment_author', table_name='whisper_comment')
    op.drop_table('whisper_comment')
    op.drop_index('uq_photo_storage_key', table_name='photo')
    op.drop_index('ix_photo_subject', table_name='photo')
    op.drop_index('ix_photo_hunter', table_name='photo')
    op.drop_index('ix_photo_feed', table_name='photo')
    op.drop_table('photo')
    op.drop_index('uq_participant_profile_participant_id', table_name='participant_profile')
    op.drop_index('ix_participant_profile_event_id', table_name='participant_profile')
    op.drop_table('participant_profile')
    # ### end Alembic commands ###
