"""initial identity + gamification

Revision ID: 9bae5c681db1
Revises: 
Create Date: 2026-07-17 20:14:03.620447
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9bae5c681db1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('venue_name', sa.Text(), nullable=True),
    sa.Column('join_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', 'archived', name='event_status'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('host_secret_hash', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_event_window')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_index('ix_event_status', 'event', ['status'], unique=False)
    op.create_index('uq_event_join_code', 'event', [sa.literal_column('lower(join_code)')], unique=True)
    op.create_table('participant',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('pseudonym', sa.Text(), nullable=False),
    sa.Column('noble_title', sa.Enum('duca', 'duchessa', 'conte', 'contessa', 'barone', 'baronessa', 'visconte', 'viscontessa', 'marchese', 'marchesa', name='participant_noble_title'), nullable=True),
    sa.Column('role', sa.Enum('guest', 'host', name='participant_role'), nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_photographable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_token_id', sa.Uuid(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role <> 'host' OR is_photographable = false", name=op.f('ck_participant_host_not_photographable')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_participant_event_id_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant'))
    )
    op.create_index('ix_participant_event_id', 'participant', ['event_id'], unique=False)
    op.create_index('uq_participant_event_pseudonym', 'participant', ['event_id', sa.literal_column('lower(pseudonym)')], unique=True)
    op.create_table('point_ledger',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('photo_created', 'subject_guessed', 'photo_solved', 'hunter_guess_bonus', 'profile_completed', 'missive_replied', 'dialogue_opened', 'dialogue_matched', 'bet_staked', 'bet_won', 'bet_refunded', 'badge_bonus', 'gazette_feature', 'moderation_penalty', 'manual_host', 'reversal', name='point_reason'), nullable=False),
    sa.Column('source_domain', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delta <> 0', name=op.f('ck_point_ledger_nonzero_delta')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_point_ledger_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_point_ledger_participant_id_participant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_ledger'))
    )
    op.create_index('ix_point_ledger_event_participant', 'point_ledger', ['event_id', 'participant_id'], unique=False)
    op.create_index('ix_point_ledger_event_reason', 'point_ledger', ['event_id', 'reason'], unique=False)
    op.create_index('uq_point_ledger_event_idem', 'point_ledger', ['event_id', 'idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_point_ledger_event_idem', table_name='point_ledger')
    op.drop_index('ix_point_ledger_event_reason', table_name='point_ledger')
    op.drop_index('ix_point_ledger_event_participant', table_name='point_ledger')
    op.drop_table('point_ledger')
    op.drop_index('uq_participant_event_pseudonym', table_name='participant')
    op.drop_index('ix_participant_event_id', table_name='participant')
    op.drop_table('participant')
    op.drop_index('uq_event_join_code', table_name='event')
    op.drop_index('ix_event_status', table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
