"""betting: bet_round + bet_stake

Revision ID: 9bc813e13279
Revises: 7c41f0a9d2b3
Create Date: 2026-07-21 16:52:37.917203
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9bc813e13279'
down_revision: str | None = '7c41f0a9d2b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_round',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('template_code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('resolution_rule', sa.Text(), nullable=False),
    sa.Column('min_stake', sa.Integer(), nullable=False),
    sa.Column('max_stake', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'open', 'locked', 'settled', 'void', name='bet_round_status'), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measurement_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_pool', sa.Integer(), server_default='0', nullable=False),
    sa.Column('winning_candidate_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('settlement_idempotency_key', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('closes_at > opens_at', name=op.f('ck_bet_round_betting_window')),
    sa.CheckConstraint('max_stake >= min_stake', name=op.f('ck_bet_round_stake_bounds')),
    sa.CheckConstraint('measurement_end >= closes_at', name=op.f('ck_bet_round_measurement_after_close')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_bet_round_event_id_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bet_round'))
    )
    op.create_index('ix_bet_round_event_status', 'bet_round', ['event_id', 'status'], unique=False)
    op.create_index('uq_bet_round_one_active', 'bet_round', ['event_id'], unique=True, postgresql_where=sa.text("status IN ('scheduled','open','locked')"))
    op.create_index('uq_bet_round_settlement_key', 'bet_round', ['settlement_idempotency_key'], unique=True)
    op.create_table('bet_stake',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_participant_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('placed', 'won', 'lost', 'refunded', 'cancelled', name='bet_stake_status'), nullable=False),
    sa.Column('payout', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_bet_stake_positive_amount')),
    sa.CheckConstraint('payout >= 0', name=op.f('ck_bet_stake_positive_payout')),
    sa.ForeignKeyConstraint(['candidate_participant_id'], ['participant.id'], name=op.f('fk_bet_stake_candidate_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_bet_stake_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_bet_stake_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['bet_round.id'], name=op.f('fk_bet_stake_round_id_bet_round'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bet_stake'))
    )
    op.create_index('ix_bet_stake_participant', 'bet_stake', ['event_id', 'participant_id'], unique=False)
    op.create_index('ix_bet_stake_round', 'bet_stake', ['round_id'], unique=False)
    op.create_index('uq_bet_stake_round_participant', 'bet_stake', ['round_id', 'participant_id'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_bet_stake_round_participant', table_name='bet_stake', postgresql_where=sa.text("status <> 'cancelled'"))
    op.drop_index('ix_bet_stake_round', table_name='bet_stake')
    op.drop_index('ix_bet_stake_participant', table_name='bet_stake')
    op.drop_table('bet_stake')
    op.drop_index('uq_bet_round_settlement_key', table_name='bet_round')
    op.drop_index('uq_bet_round_one_active', table_name='bet_round', postgresql_where=sa.text("status IN ('scheduled','open','locked')"))
    op.drop_index('ix_bet_round_event_status', table_name='bet_round')
    op.drop_table('bet_round')
    # ### end Alembic commands ###
